services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: discord-bot:latest
    container_name: discord-bot
    restart: unless-stopped
    network_mode: host
    volumes:
      - $DISK/discord-bot/config/:/app/discord-bot/config/:Z
      - $DISK/discord-bot/data/:/app/discord-bot/data/:Z
      - $DISK/discord-bot/backups/:/app/discord-bot/backups/:Z
